[colors.bright]
black = "#676767"
blue = "#6871ff"
cyan = "#5ffdff"
green = "#5ff967"
magenta = "#ff76ff"
red = "#ff6d67"
white = "#fffefe"
yellow = "#fefb67"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#0225c7"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#c930c7"
red = "#c91b00"
white = "#c7c7c7"
yellow = "#c7c400"

[colors.primary]
background = "#000000"
foreground = "#c7c7c7"

[colors.search.focused_match]
background = "#c7c7c7"
foreground = "#000000"

[colors.search.matches]
background = "#c7c7c7"
foreground = "#000000"

[colors.selection]
background = "#c7c7c7"
text = "#000000"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
