#!/usr/bin/env zsh


echo "------- BOOOTSTRAP ---------------"

# su - m
echo  $HOME
source "$HOME"/.dotfiles/config/zsh/zshrc.d/00-env.zsh
source "$HOME"/.dotfiles/lib/functions.zsh

# Creating folders
create_xdg_folders

echo "--- Dev Setup ---"


#
# apt add -q \
#     bat cmake curl fd-find git ripgrep tmux vim wget zsh


echo $HOME
# Install starship
curl -sS https://starship.rs/install.sh | sh -s -- -y

# Rust
# curl https://sh.rustup.rs -sSf | sh -s -- -y

"$HOME"/.dotfiles/bin/dotfiles-link --all
"$HOME"/.dotfiles/bin/dotfiles-setup --all


# INstalling nvim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
mv /opt/nvim-linux-x86_64 /opt/nvim
#
# ln -sfv "$HOME"/.dotfiles/systems/raspberry-pi/zsh-local "$HOME"/.config
#
# # Delete unnecessary files
# rm -f "$HOME"/.bash_history "$HOME"/.bash_logout "$HOME"/.bashrc \
#       "$HOME"/.profile "$HOME"/.zshrc "$HOME"/.zsh_history
#
chsh -s $(which zsh) $(whoami)
#
exit 0
