# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
$character"""

[directory]
truncate_to_repo = false

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[time]
format='$time '
disabled=false
