#!/usr/bin/env zsh

set -euo pipefail

# Ask sudo first
sudo -v

export PATH="$HOME/.dotfiles/bin:$PATH"

echo "--- Raspberry Pi Setup ---"

dotfiles-xdg-mkdirs

sudo apt update -yq && sudo apt upgrade -yq

sudo apt install -yqm \
    bat cmake curl fd-find git ripgrep tmux vim wget zsh

sudo apt autoremove -yq
sudo apt clean -yq

# Install starship
sudo curl -sS https://starship.rs/install.sh | sh -s -- -y

# Rust
curl https://sh.rustup.rs -sSf | sh -s -- -y

curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

dot-config --all

dot-link "systems/raspberry-pi/zsh-local" "$HOME/.config/zsh-local"

# Delete unnecessary files
rm -f "$HOME/.bash_history" "$HOME/.bash_logout" "$HOME/.bashrc" \
      "$HOME/.profile" "$HOME/.zshrc" "$HOME/.zsh_history"

sudo chsh -s "$(which zsh)" "$(whoami)"

dot-post-install --all

exit 0
