#!/usr/bin/env zsh

source "$HOME"/.dotfiles/lib/functions.zsh

# Creating folders
[ ! -d "$HOME"/.config ] && mkdir -p "$HOME"/.config

echo "--- Raspberry Pi Setup ---"

sudo apt --assume-yes update
sudo apt --assume-yes upgrade

sudo apt --assume-yes install bat
sudo apt --assume-yes install cmake
sudo apt --assume-yes install curl
sudo apt --assume-yes install fd-find
sudo apt --assume-yes install fzf
sudo apt --assume-yes install git
sudo apt --assyme-yes install ripgrep
sudo apt --assyme-yes install snapd
sudo apt --assume-yes install tmux
sudo apt --assume-yes install vim
sudo apt --assume-yes install wget
sudo apt --assume-yes install zsh

sudo apt --assume-yes autoremove

sudo curl -sS https://starship.rs/install.sh | sh -s -- -y

create_xdg_folders

run_setup_all

ln -sfv "$HOME"/.dotfiles/systems/raspberry-pi/zsh-local/ "$HOME"/.config

files_to_delete=(
"$HOME/.bash_history"
"$HOME/.bash_logout"
"$HOME/.bashrc"
"$HOME/.profile"
"$HOME/.zshrc"
"$HOME/.zsh_history"
)

for i in "${files_to_delete[@]}"
do
  if [ -f "$i" ]; then
      rm "$i"
  fi
done

sudo chsh -s $(which zsh) $(whoami)

exit 0
