#!/usr/bin/env zsh

dot-link "config/vim/vimrc" "$HOME/.vimrc"

curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall
