#!/bin/bash

session="${1:-!bedrock}"
tmux="/opt/homebrew/bin/tmux"

if $tmux has-session -t "=$session" 2>/dev/null; then
  if [[ -n ${TMUX:-} ]]; then
    $tmux switch-client -t "=$session"
  else
    $tmux attach-session -t "=$session"
  fi
else
  if [[ -n ${TMUX:-} ]]; then
    $tmux new-session -ds "$session"
    $tmux switch-client -t "=$session"
  else
    $tmux new-session -s "$session"
  fi
fi
