#!/usr/bin/env zsh

set -euo pipefail

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        {
            find ~ -maxdepth 1 -mindepth 1 -name ".dotfiles*" -type d 2>/dev/null

            [[ -d ~/Dev ]] && \
                find ~/Dev -maxdepth 1 -mindepth 1 -type d 2>/dev/null
        } |
        sort |
        fzf --prompt 'Tmux Sessionizer > '
    )
fi

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr '.' '_')

if [[ -z ${TMUX:-} ]] && ! pgrep tmux >/dev/null; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t "=$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "=$selected_name"
