#!/usr/bin/env zsh

set -euo pipefail

# Ask for sudo upfront
sudo -v

rm -rf "$HOME/.dotfiles"
git clone https://github.com/odaven/.dotfiles.git "$HOME/.dotfiles"

"$HOME/.dotfiles/systems/macos/bootstrap"
