#!/usr/bin/env zsh

set -euo pipefail

# Ask sudo first
sudo -v

export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
source "$HOME/.dotfiles/config/zsh/zshrc.d/00-env.zsh"
source "$HOME/.dotfiles/config/zsh/zshrc.d/01-load-path.zsh"


echo "--- MacOS Setup ---"

dot-xdg-mkdirs

dot-install-homebrew

brew bundle install --cleanup --file "$HOME/.dotfiles/systems/macos/Brewfile"

"$HOME/.dotfiles/systems/macos/os-settings"

dot-config --all

dot-link "systems/macos/zsh" "$HOME/.config/zsh-local"

dot-post-install --all

nvim-config dot
