#!/usr/bin/env zsh

set -euo pipefail

# Ask sudo first
sudo -v

export PATH="/opt/homebrew/bin:$PATH"
source "$HOME/.dotfiles/config/zsh/zshrc.d/00-env.zsh"
source "$HOME/.dotfiles/config/zsh/zshrc.d/01-load-path.zsh"


echo "--- MacOS Setup ---"

"$HOME/.dotfiles/bin/xdg-mkdirs"

"$HOME/.dotfiles/bin/do" brew install

brew bundle install --cleanup --file "$HOME/.dotfiles/systems/macos/Brewfile"

"$HOME/.dotfiles/systems/macos/os-settings"

"$HOME/.dotfiles/bin/do" all config

"$HOME/.dotfiles/bin/link" "systems/macos/zsh" "$HOME/.config/zsh-local"
