#!/usr/bin/env zsh

source "$HOME"/.dotfiles/lib/functions.zsh
source "$HOME"/.dotfiles/lib/brew.zsh

echo "--- MacOS Setup ---"

# Asking for sudo beforehand
sudo -v

install_brew

brew bundle install --verbose --no-lock --file "$HOME"/.dotfiles/systems/macos/Brewfile

"$HOME"/.dotfiles/systems/macos/os-settings

create_xdg_folders

run_setup_all

ln -sfv "$HOME"/.dotfiles/systems/macos/git-local "$HOME"/.config
ln -sfv "$HOME"/.dotfiles/systems/macos/zsh-local "$HOME"/.config
