#!/usr/bin/env zsh

# Disable press and hold
defaults write -g ApplePressAndHoldEnabled -bool false

# Fast keyrepeat and short delay until key repeat
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15

# F row acting as F keys
defaults write -g com.apple.keyboard.fnState -bool "true"
