#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for alacritty
}

config() {
  safe_link "$HOME/.dotfiles/config/alacritty" "$HOME/.config/alacritty"
  # TODO: implement config logic for alacritty
}

envs() {
  # Export environment variables for alacritty
  # export ALACRITTY_VAR=value
}

"$@"
