#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for bat
  echo "Installing bat..."
}

config() {
  safe_link "$HOME/.dotfiles/config/bat" "$HOME/.config/bat"
  # TODO: implement config logic for bat
}

envs() {
  # Export environment variables for bat
  # export BAT_CONFIG_PATH="$HOME/.config/bat/config"
}

"$@"

