#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for bin
    echo "Installing bin scripts..."
}

config() {
  safe_link "$HOME/.dotfiles/config/bin" "$HOME/.config/bin"
  # TODO: implement config logic for bin
}

envs() {
  # Export environment variables for bin
}

"$@"
