#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for fd
}

config() {
  safe_link "$HOME/.dotfiles/config/fd" "$HOME/.config/fd"
  # TODO: implement config logic for fd
}

envs() {
  # Export environment variables for fd
}

"$@"
