#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for fzf
}

config() {
  safe_link "$HOME/.dotfiles/config/fzf" "$HOME/.config/fzf"
  # TODO: implement config logic for fzf
}

envs() {
  # Export environment variables for fzf
}

"$@"
