#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for git
}

config() {
  safe_link "$HOME/.dotfiles/config/git" "$HOME/.config/git"
  # TODO: implement config logic for git
}

envs() {
  # Export environment variables for git
}

"$@"
