#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for ideavim
}

config() {
  safe_link "$HOME/.dotfiles/config/ideavim" "$HOME/.config/ideavim"
  # TODO: implement config logic for ideavim
}

envs() {
  # Export environment variables for ideavim
}

"$@"
