#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for iterm2
}

config() {
  safe_link "$HOME/.dotfiles/config/iterm2" "$HOME/.config/iterm2"
  # TODO: implement config logic for iterm2
}

envs() {
  # Export environment variables for iterm2
}

"$@"
