#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for lazygit
}

config() {
  safe_link "$HOME/.dotfiles/config/lazygit" "$HOME/.config/lazygit"
  # TODO: implement config logic for lazygit
}

envs() {
  # Export environment variables for lazygit
}

"$@"
