#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

rm -rf "$HOME/.local/share/nvim"
rm -rf "$HOME/.local/state/nvim"
rm -rf "$HOME/.cache/nvim"
rm -rf "$HOME/.config/nvim"

install() {
  # TODO: implement install logic for nvim
}

config() {
  safe_link "$HOME/.dotfiles/config/nvim" "$HOME/.config/nvim"
  # TODO: implement config logic for nvim
}

envs() {
  # Export environment variables for nvim
}

"$@"

