#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

rm -rf "$HOME/.local/share/nvim"
rm -rf "$HOME/.local/state/nvim"
rm -rf "$HOME/.cache/nvim"
rm -rf "$HOME/.config/nvim"

link_config "$HOME/.dotfiles/config/nvim" "$HOME/.config/nvim"

