#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for ripgrep
}

config() {
  safe_link "$HOME/.dotfiles/config/ripgrep" "$HOME/.config/ripgrep"
  # TODO: implement config logic for ripgrep
}

envs() {
  # Export environment variables for ripgrep
}

"$@"
