#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for sqlite3
}

config() {
  safe_link "$HOME/.dotfiles/config/sqlite3" "$HOME/.config/sqlite3"
  # TODO: implement config logic for sqlite3
}

envs() {
  # Export environment variables for sqlite3
}

"$@"
