#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

install() {
  # TODO: implement install logic for starship
}

config() {
  safe_link "$HOME/.dotfiles/config/starship/starship.toml" "$HOME/.config/starship.toml"
  # TODO: implement config logic for starship
}

envs() {
  # Export environment variables for starship
}

"$@"
