#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"



install() {
  # TODO: implement install logic for tmux
}

config() {
    rm -rf "$HOME/.dotfiles/config/tmux/plugins"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.dotfiles/config/tmux/plugins/tpm"

    "$HOME/.config/tmux/plugins/tpm/bin/install_plugins"
  
    safe_link "$HOME/.dotfiles/config/tmux" "$HOME/.config/tmux"
  # TODO: implement linking config for tmux
}

envs() {
  # Export environment variables for tmux
}

"$@"
