#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

rm -rf "$HOME/.dotfiles/config/tmux/plugins"
git clone https://github.com/tmux-plugins/tpm "$HOME/.dotfiles/config/tmux/plugins/tpm"

link_config "$HOME/.dotfiles/config/tmux" "$HOME/.config/tmux"

"$HOME/.config/tmux/plugins/tpm/bin/install_plugins"
