#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

link_config "$HOME/.dotfiles/config/vim/.vimrc" "$HOME/.vimrc"

curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall
