#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"



install() {
  # TODO: implement install logic for vim
}

config() {
    curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    vim +PlugInstall +qall
    
    safe_link "$HOME/.dotfiles/config/vim/.vimrc" "$HOME/.vimrc"
    # TODO: implement config logic for vim
}

envs() {
  # Export environment variables for vim
}

"$@"
