#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"

rm -rf "$HOME/.config/oh-my-zsh/"

export KEEP_ZSHRC='yes'
export ZSH="$HOME/.config/oh-my-zsh"
curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash

link_config "$HOME/.dotfiles/config/zsh" "$HOME/.config/zsh"
link_config "$HOME/.config/zsh/.zshenv" "$HOME/.zshenv"
