#!/usr/bin/env zsh

source "$HOME/.dotfiles/lib/functions.zsh"


install() {
  # TODO: implement install logic for zsh
}

config() {

    rm -rf "$HOME/.config/oh-my-zsh/"

    export KEEP_ZSHRC='yes'
    export ZSH="$HOME/.config/oh-my-zsh"
    curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash

    safe_link "$HOME/.config/zsh/.zshenv" "$HOME/.zshenv"
    safe_link "$HOME/.dotfiles/config/zsh" "$HOME/.config/zsh"
  # TODO: implement linking config for zsh
}

envs() {
  # Export environment variables for zsh
}

"$@"
