#!/usr/bin/env sh

set -euo pipefail

sudo -v

sudo apt update -q
sudo apt upgrade -yq
sudo apt install -yq git zsh

rm -rf "$HOME/.dotfiles"
git clone --depth 1 -b master https://github.com/odaven/.dotfiles.git "$HOME/.dotfiles"

"$HOME/.dotfiles/systems/pi/bootstrap"
