# Set C-a as prefix
unbind C-b
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# Tmux inside tmux
bind-key -n C-a send-prefix

######### General settings #########
set -g base-index 1
set -g display-panes-time 2000
set -g display-time 2000
set -g escape-time 0
set -g history-limit 50000
set -g monitor-activity on
set -g monitor-bell on
set -g monitor-silence 3
set -g mouse on
set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g window-size largest
set-option -g focus-events on
set-option -g set-titles on
set-option -g set-titles-string "[#S] #I:#W"
set-option -g automatic-rename on

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"


######### Pane management  #########
# Create panes in a specific direction
bind H split-window -h -b -c "#{pane_current_path}"
bind J split-window -v -c "#{pane_current_path}"
bind K split-window -v -b -c "#{pane_current_path}"
bind L split-window -h -c "#{pane_current_path}"

# Bring a pane from another window into the current window
bind P command-prompt -p "(join-pane-from)"  "join-pane -fh -s ':%%' \; select-layout even-horizontal"

# Rotate panes
bind o rotate-window

# Rename panes and windows
bind . command-prompt -p "(rename-pane)" "set-option -p @pane_label '%%'"

# Resize panes
bind -n C-S-Left resize-pane -L 5
bind -n C-S-Down resize-pane -D 5
bind -n C-S-Up resize-pane -U 5
bind -n C-S-Right resize-pane -R 5

# Layouts
bind | select-layout even-horizontal
bind \\ select-layout even-horizontal
bind - select-layout even-vertical
bind = select-layout tiled


######### Window navigation #########

# Keep current path when creating new window
bind c new-window -c "#{pane_current_path}"

# Swap windows
bind < swap-window -t -1 \; previous-window
bind > swap-window -t +1 \; next-window

# Rename currect window
bind , command-prompt -p "(rename-window)" { if -F "#{==:%%,}" "set-window-option automatic-rename on" "rename-window %%" }


######### Session management #########
# Sort session by name in tree mode
bind s choose-tree -s -O name
bind w choose-tree -w -O name

# Go to bedrock or create it if it does not exist
bind b run-shell '$HOME/.local/bin/common/tmux-init'

# Vi copypaste mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Escape send -X cancel


######### Theme #########
source-file ~/.config/tmux/themes/my-theme.conf


######### Plugins #########
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b "bash -lc '$HOME/.config/tmux/plugins/tpm/tpm'"
